version: '3.8'

services:
  # Clojure Backend API
  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: vkm-backend
    ports:
      - "3000:3000"
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATOMIC_URI=datomic:mem://vkm-graph
      - SERVER_PORT=3000
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vkm-network

  # React Frontend
  frontend:
    build:
      context: ./viz
      dockerfile: Dockerfile
    container_name: vkm-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - vkm-network

networks:
  vkm-network:
    driver: bridge

volumes:
  data:
    driver: local
